### ISSUE TITLE
创建规则页面，当把所有规则全量去除时，显示“隔提醒”

### ISSUE THREAD

**Issue by syt-honey** [syt-honey/Reminder#3]
**问题描述**
创建规则页面，当把所有规则全量去除时，显示“隔提醒”

**复现步骤**
复现步骤如下:
1. 进入首页
2. 点击“添加”任务按钮
3. 点击“添加”规则按钮
4. 去除所有的自定义规则
5. 显示 “隔提醒”

**期望的表现是怎样的？**
应该最少会选中一条规则，或者给出更好的提示语

**设备信息**
 - 微信版本:  8.0.13
 - 设备类型:  iphone12
 - 系统版本: ios 14.7.1

**附加信息**
none

**Comment by Sicolas-Flamel** [comment]
**问题描述**
设置的提醒天数和成长一览图里的并不一致.

**复现步骤**
19号的时候在一览图里面有标注，但是 Home 页没有显示子任务；
今天是 21 号，Home 页有任务，但是成长一览图里却没有标记。

![IMG_C7AB6160587B-1](https://user-images.githubusercontent.com/76936556/134151525-fb9b414f-6f1f-4ba9-b7a0-22e8793f63d3.jpeg)
![IMG_8CDA67A404CD-1](https://user-images.githubusercontent.com/76936556/134152011-8ae35476-b728-4296-8c2b-44346f237a8c.jpeg)

**设备信息**
微信版本: 8.0.12
设备类型: iPhone12
系统版本: ios 14.5
版本信息：beta-v1.0.19

**Comment by Sicolas-Flamel** [comment]
**问题描述**
在今日待办页更新任务完成状态太慢。

**复现步骤**

添加任务，在今日待办页进行左滑，点完成，会出现正在更新在转圈，转了至少一分钟，没有界面上的变化。
![IMG_CFED2966279D-1](https://user-images.githubusercontent.com/76936556/134153175-ac094b3d-faf0-459a-844d-352a553c9708.jpeg)


**设备信息**
微信版本: 8.0.12
设备类型: iPhone12
系统版本: ios 14.5
版本信息：beta-v1.0.19

**Comment by Sicolas-Flamel** [comment]
**问题描述**
还是想等一个推送，有时候会忘记打开小程序😭😭

**Comment by syt-honey** [comment]
> **问题描述**
> 还是想等一个推送，有时候会忘记打开小程序😭😭

安排！

**Comment by syt-honey** [comment]
> **问题描述**
> 创建规则页面，当把所有规则全量去除时，显示“隔提醒”
> 
> **复现步骤**
> 复现步骤如下:
> 
> 1. 进入首页
> 2. 点击“添加”任务按钮
> 3. 点击“添加”规则按钮
> 4. 去除所有的自定义规则
> 5. 显示 “隔提醒”
> 
> **期望的表现是怎样的？**
> 应该最少会选中一条规则，或者给出更好的提示语
> 
> **设备信息**
> 
> * 微信版本:  8.0.13
> * 设备类型:  iphone12
> * 系统版本: ios 14.7.1
> 
> **附加信息**
> none

beta-1.0.22 版本已修复
